#!/bin/sh
#
# Symlink the ctl commands
DEST_DIR=${1:-/opt/manifold}

TARGET=/usr/bin

error_exit()
{
	echo "${1:-"Unknown Error"}" 1>&2
	exit 1
}

create_symlink() {
	local source=${1?'Must provide a source'}
	local basename="$(basename "${source}")"
	local target="${TARGET}/${basename}"

	ln -fs "$source" "$target" || error_exit "Failed to create ${basename} symlink in ${TARGET}"
}

remove_symlink() {
	local source=${1?'Must provide a source'}

	if [ -h "${source}" ]; then
		rm "${source}" >/dev/null
	fi
}

remove_local_symlink() {
	local program=${1?'Must provide a program'}

	local sbin_source="/usr/local/sbin/${program}"
	local bin_source="/usr/local/bin/${program}"

	remove_symlink "${sbin_source}"
	remove_symlink "${bin_source}"
}

create_symlinks()
{
	create_symlink ${DEST_DIR}/bin/manifold-ctl
	create_symlink ${DEST_DIR}/bin/manifold-rake
	create_symlink ${DEST_DIR}/bin/manifold-api
	create_symlink ${DEST_DIR}/bin/manifold-psql
	create_symlink ${DEST_DIR}/bin/pandoc
	create_symlink ${DEST_DIR}/bin/pandoc-citeproc
}

remove_local_symlinks() {
	remove_local_symlink manifold-ctl
	remove_local_symlink manifold-rake
	remove_local_symlink manifold-api
	remove_local_symlink manifold-psql
	remove_local_symlink pandoc
	remove_local_symlink pandoc-citeproc
}

create_symlinks
remove_local_symlinks
