#!/bin/sh
#
# Symlink the ctl commands
DEST_DIR=${1:-/opt/manifold}

if [ -s "/etc/redhat-release" ]; then
	# RHEL uses /usr/local/sbin in the default root $PATH rather than /usr/local/bin
	TARGET="/usr/local/sbin"
else
	TARGET="/usr/local/bin"

error_exit()
{
	echo "${1:-"Unknown Error"}" 1>&2
	exit 1
}

create_symlink() {
	local source=${1?'Must provide a source'}
	local basename="$(basename "${source}")"
	local target="${TARGET}/${basename}"

	ln -fs "$source" "$target" || error_exit "Failed to create ${basename} symlink in ${TARGET}"
}

create_symlinks()
{
	create_symlink ${DEST_DIR}/bin/manifold-ctl
	create_symlink ${DEST_DIR}/bin/manifold-rake
	create_symlink ${DEST_DIR}/bin/manifold-api
	create_symlink ${DEST_DIR}/bin/manifold-psql
	create_symlink ${DEST_DIR}/bin/pandoc
	create_symlink ${DEST_DIR}/bin/pandoc-citeproc
}

create_symlinks
