#!/bin/sh
#
# Perform necessary Manifold setup steps
# after package is installed.
#
DEST_DIR=/opt/manifold
EXTERNAL_URL=http://$(hostname -f)
# Check if we have colors enabled
tput=$(which tput)
if [ -n "$tput" ]; then
  ncolors=$($tput colors)
  if [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
    RED="$(tput setaf 1)"
    GREEN="$(tput setaf 2)"
    YELLOW="$(tput setaf 3)"
    GRAY="$(tput setaf 244)"
    NOCOLOR="$(tput sgr0)"
  else
    RED=""
    GREEN=""
    YELLOW=""
    NOCOLOR=""
    GRAY=""
  fi
fi

VERSION_FILE=/opt/manifold/embedded/src/MANIFOLD_VERSION
if [ -e $VERSION_FILE ] ; then
  VERSION=$(<$VERSION_FILE)
else
  VERSION=""
fi


manifold_ascii()
{
cat <<'BANNER'
  ╦
  ░░░╬φ╦,                                               ,╓╤
  ░░░╬░░░░░╬╦╦,                                  ,╓╦φ╣╬░░░░
  ░░░    "╚╬░░░░╬▒╦╦,                     ,╓╦φ╬╬░░░░░╬╩╙"
  ░░░         `╙╩╬░░░░╬φ╦╖         ,╓╦φ╣╬░░░░░╬╩╙"
  ░░░               "╙╩░░░░░╬╦╦φ╣╬░░░░░╬╩╙"            ,╔╦φ
  ░░░                ,╓╦╬░░░░░░░░░░░░,          ,╓╦φ╬╬░░░░░
  ░░░         ,╓╦φ▒╬░░░░░╬╩╨╠░░░╙╩╬░░░░╬▒╦╦╦φ╬╬░░░░░╩╩╙`
  ░░░   ,╦φ╣╬░░░░░╬╩╨"      ]░░░     "╙╩░░░░░░░░░
  ░░░╬░░░░░░╩╨"            ,╠░░░           "╚╬░░░░░╬╦╦,╔╦ê╬
  ░░╬╩╩"            ,╓╦φ╣╬░░░░░░                `╙╩╬░░░░░░░
             ,╓╦φ╣╬░░░░░╬╩╙"╠░░░                      `║░░░
      ,╓╦φ╣╬░░░░░╬╩╙"       ]░░░                       ║░░░
  φ╣╬░░░░░╬╩╨"            ,╔╣░░░                       ║░░░
  ░╬╩╙`            ,╓╦φ╬╬░░░░░░░                       ║░░░
            ,╓╦φ╬╬░░░░░╩╩╙` ╠░░░                       ║░░░
     ,╓╦φ╣╬░░░░░╩╩"`        ]░░░                       ║░░░
  ╣╬░░░░░╩╩"`            ,╔╦╣░░░                       ║░░░
  ╬╩╙`            ,╔╦φ╬░░░░░░░░░                       ║░░░
           ,╔╦φ╬╬░░░░░╩╩"   ]░░░                       ║░░░
    ,╔╦φ╣░░░░░░╩╩"`         ]░░░                       ║░░░
  ░░░░░░╩╩"`            ,╦╦╣╬░░░╣╦╦,                   ║░░░
  ╩"`            ,╦╦╣╬░░░░░╬╩╩╙╩╬░░░░╬▒╦╖              ║░░░
         ,,╦╦▒╬░░░░░╬╩╙"           `╙╩╬░░░░╬φ╦╓        ║░░░
   ,╦╦ê╣░░░░░░╩╨"                        "╚╬░░░░░╣╦╦,  ║░░░
  ░░░░░╩╩"                                    `╙╩╬░░░░╬╬░░░
  "                                                 `╙╩╬░░░
                                                          "
BANNER
}

border()
{
    title="| $1 |"
    edge=$(echo "$title" | sed 's/./-/g')
    echo "$edge"
    echo "$title"
    echo "$edge"
}
print_banner()
{


    echo ""
    echo "$GREEN"
    echo "                  Manifold Scholarship $VERSION"
    echo "$(manifold_ascii)"
    echo "$NOCOLOR"
    echo ""
}

create_config_template()
{
  # Create a minimal manifold.rb template if /etc/manifold/manifold.rb does not exist.
  if ! [ -e /etc/manifold/manifold.rb ] ; then
    mkdir -p /etc/manifold
    cp "${DEST_DIR}/etc/manifold.rb" /etc/manifold/manifold.rb
    sed -i 's!GENERATED_EXTERNAL_URL!'$EXTERNAL_URL'!g' /etc/manifold/manifold.rb
    chmod 600 /etc/manifold/manifold.rb
  else
    EXTERNAL_URL=$(awk '/^external_url/ { print $2 }' /etc/manifold/manifold.rb | tr -d "'\"")
  fi
}

current_version()
{
  VERSION=/opt/manifold/embedded/src/MANIFOLD_VERSION
  if [ -e $VERSION ] ; then
    value=$(<$VERSION)
    return "$value"
  fi
}

print_welcome()
{
  print_banner
  echo "To configure and start Manifold, run the following command:"
  echo "$GRAY"
  echo "sudo manifold-ctl reconfigure"
  echo "$NOCOLOR"

  if ! test -z "$EXTERNAL_URL"; then
    echo "Manifold should be reachable at:"
    echo "$GRAY"
    echo "$EXTERNAL_URL"
    echo "$NOCOLOR"
  fi

  echo "Configure Manifold for your system by editing this file and running reconfigure:"
  echo "$GRAY"
  echo "/etc/manifold/manifold.rb"
  echo "$NOCOLOR"
}

create_config_template
print_welcome

if test -f "${DEST_DIR}/embedded/bin/symlink_ctl_cmds"; then
  ${DEST_DIR}/embedded/bin/symlink_ctl_cmds ${DEST_DIR}
fi

