#!/bin/sh

# RPM only
# It is run at the very end of an install/upgrade of the package
# It is NOT run on removal of the package
DEST_DIR=/opt/manifold

case "$1" in
  0)
    # RPM install/upgrade
    ${DEST_DIR}/embedded/bin/symlink_ctl_cmds ${DEST_DIR}
    ${DEST_DIR}/bin/manifold-ctl upgrade
    ;;
  *)
    # Noop.
    ;;
esac