#!/bin/sh
#
# Perform necessary manifold setup steps
# before package is installed.
#

echo "You're about to install manifold!"

stop_current_manifold() {
	local manifold_ctl="$(which manifold-ctl)"

	if [ -z "$manifold_ctl" -o ! -x "${manifold_ctl}" ]; then
		return
	fi

	echo "Detected an existing manifold installation"

	if "$manifold_ctl" status | grep --no-messages '^run:' >/dev/null; then
		echo "Stopping existing manifold..."
		"$manifold_ctl" stop cable
		"$manifold_ctl" stop client
		"$manifold_ctl" stop clockwork
		"$manifold_ctl" stop elasticsearch
		"$manifold_ctl" stop postgresql
		"$manifold_ctl" stop puma
		"$manifold_ctl" stop redis
		"$manifold_ctl" stop sidekiq
	fi
}

stop_current_manifold
